apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-webapp-deployment
  labels:
    app: resume-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-webapp
  template:
    metadata:
      labels:
        app: resume-webapp
    spec:
      containers:
        - name: resume-webapp
          image: bb1296/resume:<TAG>
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: resume-webapp-service
spec:
  type: NodePort
  selector:
    app: resume-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080